#!/usr/bin/env escript

main(_Args) ->
    code:add_pathz("./ebin"),
    Expected = [number, int, sint, float, atom, bool, map, restricted_map, state,
                list, tuple, string, binary, pid, reference],
    Expected = datatypes:all(),
    [true = datatypes:is_type(Type) || Type <- Expected],
    false = datatypes:is_type(var),
    [int, sint] = datatypes:integer_types(),
    [map, restricted_map, state, list, tuple] = datatypes:aggregate_types(),
    [string, binary] = datatypes:text_types(),
    [pid, reference] = datatypes:beam_handle_types(),
    [var] = datatypes:meta_types(),
    true = datatypes:is_number_type(sint),
    true = datatypes:is_integer_type(int),
    true = datatypes:is_scalar_type(string),
    true = datatypes:is_aggregate_type(restricted_map),
    true = datatypes:is_text_type(binary),
    true = datatypes:is_beam_handle_type(pid),
    false = datatypes:is_constructible(pid),
    false = datatypes:is_constructible(binary),
    true = datatypes:is_constructible(string),
    true = datatypes:crosses_erlang_ffi({named, "Player"}),
    false = datatypes:crosses_erlang_ffi({pointer, int}),
    false = datatypes:crosses_process({strict_pointer, string}),
    true = datatypes:is_pointer_type({strict_pointer, {pointer, int}}),
    true = datatypes:is_named_type({named, "Result"}),
    "*Int" = datatypes:display_name({pointer, int}),
    "strict **String" = datatypes:display_name({strict_pointer, {pointer, string}}),
    #{kind := number, category := numeric, children := [int, sint, float],
      erlang_ffi := true, process_message := true,
      capabilities := NumberCapabilities} = datatypes:type_info(number),
    true = lists:member(orderable, NumberCapabilities),
    #{kind := restricted_map, category := aggregate,
      capabilities := RestrictedCapabilities} = datatypes:type_info(restricted_map),
    true = lists:member(bounded, RestrictedCapabilities),
    #{kind := state, category := aggregate, constructible := true,
      erlang_ffi := true, process_message := true,
      capabilities := StateCapabilities} = datatypes:type_info(state),
    true = lists:member(state_snapshot, StateCapabilities),
    #{kind := pointer, category := pointer, pointee := int,
      erlang_ffi := false, process_message := false} =
        datatypes:type_info({pointer, int}),
    #{kind := named, category := user_defined, display := "Player"} =
        datatypes:type_info({named, "Player"}),
    io:format("data type tests passed~n").
